### ISSUE TITLE
Consider using cargo-generate

### ISSUE THREAD

**Issue by fubuloubu** [shawntabrizi/substrate-package#16]
Homepage: https://crates.io/crates/cargo-generate

Seems like it would help the current setup process a bit

**Comment by shawntabrizi** [comment]
This looks like a great suggestion, I will look into it :)

**Comment by shawntabrizi** [comment]
I think this is not the right choice since it requires the user always "clone" their project with `cargo-generate`.

If you clone a project set up this way directly, such as: https://github.com/ashleygwilliams/wasm-pack-template

And you run cargo build, you get the following error:

```
Shawns-MBP:wasm-pack-template shawntabrizi$ cargo build
error: failed to parse manifest at `/Users/shawntabrizi/Documents/GitHub/wasm-pack-template/Cargo.toml`

Caused by:
  Invalid character `{` in package name: `{{project-name}}`
Shawns-MBP:wasm-pack-template shawntabrizi$ 
```

I think it is important to make sure that the project still works using the basics.
