### ISSUE TITLE
Should package incude subkey?

### ISSUE THREAD

**Issue by JoshOrndorff** [shawntabrizi/substrate-package#25]
I started revising the private network tutorial for Substrate v2.0. Specifically I wanted to write against Substrate Package v1.5.0 which I cut today and is a pre-v2.0 . One of the first things users have to do is generate their own keys using subkey, and I didn't know how to write against package.

**Comment by riusricardo** [comment]
I prefer not to add it. It doesn't makes much sense to me because the user will only use the code to install it and then it is not used again.  We can modify the getsubstrate script for this need and enable a option for installing only subkey or add the command to the readme.
It can be installed by running: 
`cargo install --force --git https://github.com/paritytech/substrate subkey`

**Comment by JoshOrndorff** [comment]
I agree with your point that they won't hack on it.

How do you think we should help people get a version of subkey that is known to be compatible with the node they're building from Substrate Package? If they install a subkey that doesn't match their node, they may generate incompatible keys.

**Comment by shawntabrizi** [comment]
All the features of subkey (besides maybe some level of security) should be available in the Polkadot JS API.

Look at "keyring".

Maybe there should be some "easy instructions" for generating keys for tutorials, but a **Note** that to generate keys properly, they should visit another page with instructions
